package com.kylemiles.mockdraftsjdbc.entity;

public enum Pick {
	
	  ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, 
	  NINE, TEN, ELEVEN, TWELVE, THIRTEEN, FOURTEEN, FIFTEEN, SIXTEEN, 
	  SEVENTEEN, EIGHTEEN, NINETEEN, TWENTY,TWENTYONE, TWENTYTWO, TWENTYTHREE, TWENTYFOUR, 
	  TWENTYFIVE, TWENTYSIX, TWENTYSEVEN, TWENTYEIGHT, TWENTYNINE, THIRTY, THIRTYONE, THIRTYTWO, 
	  THIRTYTHREE, THIRTYFOUR, THIRTYFIVE, THIRTYSIX, THIRTYSEVEN, THIRTYEIGHT, THIRTYNINE, FORTY, 
	  FORTYONE, FORTYTWO, FORTYTHREE

}
