package com.kylemiles.mockdraftsjdbc.entity;

public enum Rank {
	
	  ONE(1), TWO(2), THREE(3), FOUR(4), FIVE(5), SIX(6), SEVEN(7), EIGHT(8), 
	  NINE(9), TEN(10), ELEVEN(11), TWELVE(12), THIRTEEN(13), FOURTEEN(14), FIFTEEN(15), SIXTEEN(16), 
	  SEVENTEEN(17), EIGHTEEN(18), NINETEEN(19), TWENTY(20),TWENTYONE(21), TWENTYTWO(22), TWENTYTHREE(23), TWENTYFOUR(24), 
	  TWENTYFIVE(25), TWENTYSIX(26), TWENTYSEVEN(27), TWENTYEIGHT(28), TWENTYNINE(29), THIRTY(30), THIRTYONE(31), THIRTYTWO(32), 
	  THIRTYTHREE(33), THIRTYFOUR(34), THIRTYFIVE(35), THIRTYSIX(36), THIRTYSEVEN(37), THIRTYEIGHT(38), THIRTYNINE(39), FORTY(40), 
	  FORTYONE(41), FORTYTWO(42), FORTYTHREE(43), FORTYFOUR(44), FORTYFIVE(45), FORTYSIX(46), FORTYSEVEN(47), FORTYEIGHT(48), FORTYNINE(49),
	  FIFTY(50);
	
	private int rankValue;

	Rank(int rankValue) {
		this.rankValue = rankValue;
	}

	public int getRankValue() {
		return rankValue;
	}

}
